// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config"; // load .env
import { config as loadLocalEnv } from "dotenv";

// .env.local (Next.js) not loaded automatically by dotenv/config.
// override priority: system env → .env.local → .env
loadLocalEnv({ path: ".env.local", override: false });

import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});